"""add chat_documents scope table

Revision ID: 8253dce212e2
Revises: 83bb91f9faf2
Create Date: 2026-07-04 23:25:29.991491
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8253dce212e2'
down_revision = '83bb91f9faf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'document_id', name='uq_chat_document')
    )
    op.create_index(op.f('ix_chat_documents_chat_id'), 'chat_documents', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_documents_document_id'), 'chat_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_chat_documents_user_id'), 'chat_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_documents_user_id'), table_name='chat_documents')
    op.drop_index(op.f('ix_chat_documents_document_id'), table_name='chat_documents')
    op.drop_index(op.f('ix_chat_documents_chat_id'), table_name='chat_documents')
    op.drop_table('chat_documents')
    # ### end Alembic commands ###

